AllupBackendProject/Models/Feature.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AllupBackendProject.Models
{
    public class Feature
    {
        public int Id { get; set; }
        public string BannerTitle { get; set; }
        public string BannerText { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped] 
        [Required]
        public IFormFile Photo { get; set; }
    }
}

AllupBackendProject/Areas/AdminArea/Controllers/FeatureController.cs
using AllupBackendProject.DAL;
using AllupBackendProject.Models;
using FrontToBack.Extensions;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace AllupBackendProject.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class FeatureController : Controller
    {
        private readonly Context _context;
        private readonly IWebHostEnvironment _env;

        public FeatureController(Context context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            IEnumerable<Feature> features = _context.Features.ToList();
            return View(features);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Feature feature)
        {
            if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                ModelState.AddModelError("Photo", "Do not empty");
            }
            if (!feature.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "Please upload only image files");
                return View();
            }
            if (feature.Photo.IsCorrectSize(300))
            {
                ModelState.AddModelError("Photo", "The photo size cannot be more than 300");
                return View();
            }
            Feature newFeature = new Feature();

            string fileName = await feature.Photo.SaveImageAsync(_env.WebRootPath, "banner-icon");
            newFeature.ImageUrl = fileName;
            newFeature.BannerText = feature.BannerText;
            newFeature.BannerTitle = feature.BannerTitle;
            await _context.Features.AddAsync(newFeature);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Feature dbFeature = await _context.Features.FindAsync(id);
            if (dbFeature == null) return NotFound();
            return View(dbFeature);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteSlider(int? id)
        {
            if (id == null) return NotFound();
            Feature dbFeature = await _context.Features.FindAsync(id);
            if (dbFeature == null) return NotFound();

            string path = Path.Combine(_env.WebRootPath, "banner-icon", dbFeature.ImageUrl);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            _context.Features.Remove(dbFeature);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return NotFound();
            Feature dbFeature = await _context.Features.FindAsync(id);
            if (dbFeature == null) return NotFound();
            return View(dbFeature);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(int? id, Feature feature)
        {
            if (feature.Photo != null)
            {
                if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                {
                    ModelState.AddModelError("Photo", "Do not empty");
                }
                if (!feature.Photo.IsImage())
                {
                    ModelState.AddModelError("Photo", "Please upload only image files");
                    return View();
                }
                if (feature.Photo.IsCorrectSize(300))
                {
                    ModelState.AddModelError("Photo", "The photo size cannot be more than 300");
                    return View();
                }
                Feature dbFeature = await _context.Features.FindAsync(id);
                string path = Path.Combine(_env.WebRootPath, "banner-icon", dbFeature.ImageUrl);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
                string filename = await feature.Photo.SaveImageAsync(_env.WebRootPath, "banner-icon");
                dbFeature.ImageUrl = filename;
                dbFeature.BannerTitle = feature.BannerTitle;
                dbFeature.BannerText = feature.BannerText;

                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return NotFound();
            Feature dbFeature = await _context.Features.FindAsync(id);
            if (dbFeature == null) return NotFound();
            return View(dbFeature);
        }
    }
}

AllupBackendProject/Areas/AdminArea/Views/Feature/Create.cshtml
@model Feature
@{ ViewData["Title"] = "Create"; }

<div class="container">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Default form</h4>
                    <p class="card-description">
                        Create Slider Form
                    </p>
                    <form class="forms-sample" method="Post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label asp-for="Photo"></label>
                            <input asp-for="Photo" class="form-control" accept="image/*" placeholder="Name">
                            <span asp-validation-for="Photo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="BannerTitle"></label>
                            <input asp-for="BannerTitle" class="form-control" placeholder="MainTitle">
                            <span asp-validation-for="BannerTitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="BannerText"></label>
                            <input asp-for="BannerText" class="form-control" placeholder="SubTitle">
                            <span asp-validation-for="BannerText" class="text-danger"></span>
                        </div>
                        <button class="btn btn-light">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
@section Scripts{

    <partial name="_Validation">

}

AllupBackendProject/Areas/AdminArea/Views/Feature/Delete.cshtml
@model Feature
@{ ViewData["Title"] = "Delete"; }

<div class="container">
    <div class="row">
        <form class="forms-sample mt-3" method="Post">
            <button class="btn btn-light">Delete</button>
        </form>
        <div class="col-6">
            <a asp-controller="Feature" asp-action="Index" class="btn btn-warning">Go Back</a>
        </div>
    </div>
</div>

AllupBackendProject/Areas/AdminArea/Views/Feature/Detail.cshtml
@model Feature
@{ ViewData["Title"] = "Detail"; }

<div class="container">
    <div class="row">
        <div class="col-6">
            <img style="width:250px; height:150px" src="~/banner-icon/@Model.ImageUrl" /><br />
            <span>Feature Title:</span>
            <p>@Model.BannerTitle</p>
            <span>Feature Text:</span>
            <p>@Model.BannerText</p>
            <div class="col-6">
                <a asp-controller="Feature" asp-action="Index" class="btn btn-warning">Go Back</a>
            </div>
        </div>
    </div>
</div>

AllupBackendProject/Areas/AdminArea/Views/Feature/Index.cshtml
@model IEnumerable<Feature>
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Basic Table</h4>
            <p class="card-description">
                <a class="btn btn-primary" asp-controller="Feature" asp-action="Create"> Create Feature</a>
            </p>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Settings</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
            <tr>
                <td>
                    <img style="width:150px; height:150px" src="~/banner-icon/@item.ImageUrl" />
                </td>
                <td>
                    <a asp-controller="Feature" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-account-remove"></i></a>
                    <a asp-controller="Feature" asp-action="Update" asp-route-id="@item.Id" class="btn btn-inverse-primary"><i class="mdi mdi-account-edit"></i></a>
                    <a asp-controller="Feature" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-info"><i class="mdi mdi-account-details"></i></a>
                </td>
            </tr>}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

AllupBackendProject/Areas/AdminArea/Views/Feature/Update.cshtml
@model Feature
@{ ViewData["Title"] = "Update"; }

<div class="container">
    <div class="row">
        <div class="col-6">
            <img style="width:150px; height:150px" src="~/banner-icon/@Model.ImageUrl" />
            <form class="forms-sample" method="Post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Photo"></label>
                    <input asp-for="Photo" class="form-control" accept="image/*" placeholder="Name">
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>
                <p>@Model.BannerTitle</p>
                <div class="form-group">
                    <label asp-for="BannerTitle"></label>
                    <input asp-for="BannerTitle" class="form-control" placeholder="MainTitle">
                    <span asp-validation-for="BannerTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p>@Model.BannerText</p>
                    <label asp-for="BannerText"></label>
                    <textarea asp-for="BannerText" class="form-control" placeholder="SubTitle"></textarea>
                    <span asp-validation-for="BannerText" class="text-danger"></span>
                </div>
                <div class="col-6">
                    <a asp-controller="Feature" asp-action="Index" class="btn btn-warning">Go Back</a>
                </div>
                <button class="btn btn-light">Update</button>
            </form>
        </div>
    </div>
</div>